// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "stocks_calculator/internal/model"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// AddGroups provides a mock function with given fields: ctx, userId, groups
func (_m *App) AddGroups(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for AddGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddStocks provides a mock function with given fields: ctx, userId, stocks
func (_m *App) AddStocks(ctx context.Context, userId int, stocks []model.Stock) error {
	ret := _m.Called(ctx, userId, stocks)

	if len(ret) == 0 {
		panic("no return value specified for AddStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Stock) error); ok {
		r0 = rf(ctx, userId, stocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProfile provides a mock function with given fields: ctx, profile, userId
func (_m *App) CreateProfile(ctx context.Context, profile model.Profile, userId int) error {
	ret := _m.Called(ctx, profile, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Profile, int) error); ok {
		r0 = rf(ctx, profile, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, data
func (_m *App) CreateUser(ctx context.Context, data model.AuthModel) (*model.AuthResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthModel) (*model.AuthResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthModel) *model.AuthResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AuthModel) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStocks provides a mock function with given fields: ctx, userId, names
func (_m *App) FindStocks(ctx context.Context, userId int, names []string) ([]model.FoundStock, error) {
	ret := _m.Called(ctx, userId, names)

	if len(ret) == 0 {
		panic("no return value specified for FindStocks")
	}

	var r0 []model.FoundStock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) ([]model.FoundStock, error)); ok {
		return rf(ctx, userId, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) []model.FoundStock); ok {
		r0 = rf(ctx, userId, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundStock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []string) error); ok {
		r1 = rf(ctx, userId, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, userId
func (_m *App) GetGroups(ctx context.Context, userId int) ([]model.Group, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Group, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Group); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfiles provides a mock function with given fields: ctx, userId
func (_m *App) GetProfiles(ctx context.Context, userId int) ([]model.Profile, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []model.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Profile, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Profile); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStocks provides a mock function with given fields: ctx, userId
func (_m *App) GetStocks(ctx context.Context, userId int) ([]model.Stock, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetStocks")
	}

	var r0 []model.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Stock, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Stock); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, data
func (_m *App) Login(ctx context.Context, data model.AuthModel) (*model.AuthResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthModel) (*model.AuthResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthModel) *model.AuthResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AuthModel) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rebalance provides a mock function with given fields: ctx, userId, noSell, valueDiff
func (_m *App) Rebalance(ctx context.Context, userId int, noSell bool, valueDiff float64) (model.RebalanceResponse, error) {
	ret := _m.Called(ctx, userId, noSell, valueDiff)

	if len(ret) == 0 {
		panic("no return value specified for Rebalance")
	}

	var r0 model.RebalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, float64) (model.RebalanceResponse, error)); ok {
		return rf(ctx, userId, noSell, valueDiff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, float64) model.RebalanceResponse); ok {
		r0 = rf(ctx, userId, noSell, valueDiff)
	} else {
		r0 = ret.Get(0).(model.RebalanceResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool, float64) error); ok {
		r1 = rf(ctx, userId, noSell, valueDiff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, refToken
func (_m *App) RefreshToken(ctx context.Context, refToken string) (*model.Token, error) {
	ret := _m.Called(ctx, refToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Token, error)); ok {
		return rf(ctx, refToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Token); ok {
		r0 = rf(ctx, refToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveGroups provides a mock function with given fields: ctx, userId, groups
func (_m *App) RemoveGroups(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveProfile provides a mock function with given fields: ctx, profile, userId
func (_m *App) RemoveProfile(ctx context.Context, profile model.Profile, userId int) error {
	ret := _m.Called(ctx, profile, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Profile, int) error); ok {
		r0 = rf(ctx, profile, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveStocks provides a mock function with given fields: ctx, userId, stocks
func (_m *App) RemoveStocks(ctx context.Context, userId int, stocks []model.Stock) error {
	ret := _m.Called(ctx, userId, stocks)

	if len(ret) == 0 {
		panic("no return value specified for RemoveStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Stock) error); ok {
		r0 = rf(ctx, userId, stocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RenameGroup provides a mock function with given fields: ctx, userId, group
func (_m *App) RenameGroup(ctx context.Context, userId int, group model.RenameGroupBody) error {
	ret := _m.Called(ctx, userId, group)

	if len(ret) == 0 {
		panic("no return value specified for RenameGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, model.RenameGroupBody) error); ok {
		r0 = rf(ctx, userId, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDefaultProfile provides a mock function with given fields: ctx, profile, userId
func (_m *App) SetDefaultProfile(ctx context.Context, profile model.Profile, userId int) error {
	ret := _m.Called(ctx, profile, userId)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Profile, int) error); ok {
		r0 = rf(ctx, profile, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWeights provides a mock function with given fields: ctx, userId, groups
func (_m *App) UpdateWeights(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWeights")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApp creates a new instance of App. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *App {
	mock := &App{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
