// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "stocks_calculator/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MoexApi is an autogenerated mock type for the MoexApi type
type MoexApi struct {
	mock.Mock
}

// FindStocks provides a mock function with given fields: ctx, names
func (_m *MoexApi) FindStocks(ctx context.Context, names []string) []model.MoexFindResult {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for FindStocks")
	}

	var r0 []model.MoexFindResult
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.MoexFindResult); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MoexFindResult)
		}
	}

	return r0
}

// GetPrices provides a mock function with given fields: ctx, codes
func (_m *MoexApi) GetPrices(ctx context.Context, codes []string) []model.MoexPriceResult {
	ret := _m.Called(ctx, codes)

	if len(ret) == 0 {
		panic("no return value specified for GetPrices")
	}

	var r0 []model.MoexPriceResult
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.MoexPriceResult); ok {
		r0 = rf(ctx, codes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MoexPriceResult)
		}
	}

	return r0
}

// NewMoexApi creates a new instance of MoexApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoexApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MoexApi {
	mock := &MoexApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
