// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "stocks_calculator/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateNewUser provides a mock function with given fields: ctx, user, hash
func (_m *Repository) CreateNewUser(ctx context.Context, user string, hash string) (int, error) {
	ret := _m.Called(ctx, user, hash)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, user, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, user, hash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByUsername provides a mock function with given fields: ctx, user
func (_m *Repository) FindUserByUsername(ctx context.Context, user string) (model.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, userId
func (_m *Repository) GetGroups(ctx context.Context, userId int) ([]model.Group, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Group, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Group); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfiles provides a mock function with given fields: ctx, userId
func (_m *Repository) GetProfiles(ctx context.Context, userId int) ([]model.Profile, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []model.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Profile, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Profile); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStocks provides a mock function with given fields: ctx, userId
func (_m *Repository) GetStocks(ctx context.Context, userId int) ([]model.Stock, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetStocks")
	}

	var r0 []model.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Stock, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Stock); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertGroups provides a mock function with given fields: ctx, userId, groups
func (_m *Repository) InsertGroups(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for InsertGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertProfile provides a mock function with given fields: ctx, profile, userId, def
func (_m *Repository) InsertProfile(ctx context.Context, profile string, userId int, def bool) error {
	ret := _m.Called(ctx, profile, userId, def)

	if len(ret) == 0 {
		panic("no return value specified for InsertProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, bool) error); ok {
		r0 = rf(ctx, profile, userId, def)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRefreshToken provides a mock function with given fields: ctx, userId, ref
func (_m *Repository) InsertRefreshToken(ctx context.Context, userId int, ref string) error {
	ret := _m.Called(ctx, userId, ref)

	if len(ret) == 0 {
		panic("no return value specified for InsertRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userId, ref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertStocks provides a mock function with given fields: ctx, userId, stocks
func (_m *Repository) InsertStocks(ctx context.Context, userId int, stocks []model.Stock) error {
	ret := _m.Called(ctx, userId, stocks)

	if len(ret) == 0 {
		panic("no return value specified for InsertStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Stock) error); ok {
		r0 = rf(ctx, userId, stocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveGroups provides a mock function with given fields: ctx, userId, groups
func (_m *Repository) RemoveGroups(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveProfile provides a mock function with given fields: ctx, profile, userId
func (_m *Repository) RemoveProfile(ctx context.Context, profile string, userId int) error {
	ret := _m.Called(ctx, profile, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, profile, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveStocks provides a mock function with given fields: ctx, userId, stocks
func (_m *Repository) RemoveStocks(ctx context.Context, userId int, stocks []model.Stock) error {
	ret := _m.Called(ctx, userId, stocks)

	if len(ret) == 0 {
		panic("no return value specified for RemoveStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Stock) error); ok {
		r0 = rf(ctx, userId, stocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDefaultProfile provides a mock function with given fields: ctx, profile, userId
func (_m *Repository) SetDefaultProfile(ctx context.Context, profile string, userId int) error {
	ret := _m.Called(ctx, profile, userId)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, profile, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroupName provides a mock function with given fields: ctx, userId, nameOld, nameNew
func (_m *Repository) UpdateGroupName(ctx context.Context, userId int, nameOld string, nameNew string) error {
	ret := _m.Called(ctx, userId, nameOld, nameNew)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = rf(ctx, userId, nameOld, nameNew)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStocksAmount provides a mock function with given fields: ctx, userId, stocks, amountDiff
func (_m *Repository) UpdateStocksAmount(ctx context.Context, userId int, stocks []model.Stock, amountDiff []int) error {
	ret := _m.Called(ctx, userId, stocks, amountDiff)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStocksAmount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Stock, []int) error); ok {
		r0 = rf(ctx, userId, stocks, amountDiff)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWeights provides a mock function with given fields: ctx, userId, groups
func (_m *Repository) UpdateWeights(ctx context.Context, userId int, groups []model.Group) error {
	ret := _m.Called(ctx, userId, groups)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWeights")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []model.Group) error); ok {
		r0 = rf(ctx, userId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserIdByRefreshToken provides a mock function with given fields: ctx, refToken
func (_m *Repository) UserIdByRefreshToken(ctx context.Context, refToken string) (int, error) {
	ret := _m.Called(ctx, refToken)

	if len(ret) == 0 {
		panic("no return value specified for UserIdByRefreshToken")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, refToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, refToken)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
