// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "stocks_calculator/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

// ExtractClaims provides a mock function with given fields: tokenStr
func (_m *TokenManager) ExtractClaims(tokenStr string) (model.Claims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ExtractClaims")
	}

	var r0 model.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.Claims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) model.Claims); ok {
		r0 = rf(tokenStr)
	} else {
		r0 = ret.Get(0).(model.Claims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateJWT provides a mock function with given fields: userId
func (_m *TokenManager) GenerateJWT(userId int) (model.Token, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Token, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) model.Token); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(model.Token)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateRefreshToken provides a mock function with no fields
func (_m *TokenManager) GenerateRefreshToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
