basePath: /
definitions:
  model.AuthModel:
    properties:
      pass:
        type: string
      user:
        type: string
    type: object
  model.AuthResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: string
      profiles:
        items:
          $ref: '#/definitions/model.Profile'
        type: array
      refToken:
        type: string
    type: object
  model.Profile:
    properties:
      default:
        type: boolean
      name:
        type: string
    type: object
host: localhost:3333
info:
  contact: {}
  title: Stocks Calculator API
  version: "1.0"
paths:
  /createuser:
    post:
      consumes:
      - application/json
      description: Create user with username and password
      parameters:
      - description: Create user credentials
        in: body
        name: authmodel
        required: true
        schema:
          $ref: '#/definitions/model.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "400":
          description: incorrect request body format
          schema:
            type: string
        "409":
          description: user exists
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: CreateUser
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      description: Log in with username and password
      parameters:
      - description: Login credentials
        in: body
        name: authmodel
        required: true
        schema:
          $ref: '#/definitions/model.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "400":
          description: incorrect request body format
          schema:
            type: string
        "401":
          description: wrong credentials
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Login
      tags:
      - auth
swagger: "2.0"
